- name: Loops Demo
  hosts: localhost
  connection: local
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: Hello - {{ item }}
      loop:
        - one
        - two

    - name: Loop1
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, Cost - {{ item.cost }}
      loop:
        - {name: Orange, cost: 2$ }
        - {name: Apple, cost: 1$ }

